/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.paginas;

import auxiliar.Validacoes;
import controller.CompartimentoController;
import controller.ResponsavelController;
import controller.TipoCompartimentoController;
import java.util.List;
import javax.swing.JOptionPane;
import model.Responsavel;
import model.TipoCompartimento;

/**
 *
 * @author elton
 */
public class AdicionaCompartimento extends javax.swing.JPanel implements Formulario{

    /**
     * Creates new form AdicionaCompartimento
     */
    public AdicionaCompartimento() {
        initComponents();
        preencherComboBoxCargo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        designacao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tipo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        responsavel = new javax.swing.JComboBox();
        addResponsavelJB = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricao = new javax.swing.JTextArea();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Adiciona Novo Compartimento");

        jLabel2.setText("Designacao:");

        designacao.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        designacao.setToolTipText("Designacao do compartimento, que Distingue de outros compartimentos");

        jLabel3.setText("Tipo:");

        tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Responsavel:");

        responsavel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addResponsavelJB.setText("+");

        jLabel6.setText("Descricao:");

        descricao.setColumns(20);
        descricao.setRows(5);
        jScrollPane1.setViewportView(descricao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(115, 115, 115)
                        .addComponent(responsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addResponsavelJB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(designacao)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(designacao, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(responsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addResponsavelJB))
                .addContainerGap(108, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addResponsavelJB;
    private javax.swing.JTextArea descricao;
    private javax.swing.JTextField designacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox responsavel;
    private javax.swing.JComboBox tipo;
    // End of variables declaration//GEN-END:variables
    
    private CompartimentoController compartimentoController 
            = new CompartimentoController();
    private TipoCompartimentoController tcc
            = new TipoCompartimentoController();
    private ResponsavelController responsavelController 
            = new ResponsavelController();
    
    private String erro = "";
    
    private Validacoes validacoes = new Validacoes();
    
    private String descricaoTXT;
    private String designacaoTXT;
    private TipoCompartimento tipoTXT;
    private Responsavel responsavelTXT;
    
    @Override
    public void recebe() {
        descricaoTXT = descricao.getText();
        designacaoTXT = designacao.getText();
        tipoTXT = (TipoCompartimento)tipo.getSelectedItem();
        responsavelTXT = (Responsavel)responsavel.getSelectedItem();
    }

    @Override
    public boolean isValido() {
        boolean isErro = true;
        
        return isErro;
    }

    @Override
    public boolean envia() {
        recebe();
        if(isValido()){
            boolean ev;
            ev = compartimentoController.adicionar(designacaoTXT, descricaoTXT, descricaoTXT, tipoTXT);
            if(ev){
                JOptionPane.showMessageDialog(null, "Adicionado Com Sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                limpaTudo();
                return true;
            }else{
                JOptionPane.showMessageDialog(null, "Ocorreu um Erro..BD", "dados incorr", JOptionPane.INFORMATION_MESSAGE);
               // limpaTudo();
                return false;
            }
        }else{
            JOptionPane.showMessageDialog(null, erro, "dados incorrectos", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
    }

    @Override
    public void limpaTudo() {
        descricao.setText("");
        designacao.setText("");
        tipo.setSelectedItem(0);
        responsavel.setSelectedItem(0);
    }
    
    private void preencherComboBoxCargo(){
        tipo.removeAllItems();
        responsavel.removeAllItems();
        
        List<TipoCompartimento> compartimentos 
                = (List<TipoCompartimento>)tcc.getTipoCompartimentos();
        List<Responsavel> responsavels = (List<Responsavel>)responsavelController.getResponsavels();
        
        for (TipoCompartimento tc: compartimentos) {
            tipo.addItem(tc);
        }
        
        for(Responsavel r: responsavels){
            responsavel.addItem(r);
        }
    }
}
