package visao.paginas;

import controller.FornecedorController;
import controller.FornecimentoController;
import controller.GrupoMaterialController;
import controller.MaterialController;
import java.awt.LayoutManager;
import java.sql.Date;
import java.util.Calendar;
import java.util.List;
import model.Fornecedor;
import model.Material;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author elton
 */
public class AdicionaMaterialSP extends javax.swing.JPanel implements Formulario{

    /**
     * Creates new form AdicionaMaterialSP
     */
    public AdicionaMaterialSP(){
        initComponents();
        preencherComboBoxCargo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fornecedor = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tipo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        garantia = new javax.swing.JTextField();
        qtdGarantia = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        quantidadeMaterial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        preco = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Dados do Fornecimento");

        jLabel2.setText("Fornecedor: ");

        fornecedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("+");

        jLabel3.setText("Tipo de Fornecimento:");

        tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Compra", "Doacao" }));

        jLabel4.setText("Guarantia:");

        qtdGarantia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dias", "Semanas", "Meses" }));

        jLabel5.setText("Quantidade: ");

        jLabel6.setText("Preco");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fornecedor, 0, 332, Short.MAX_VALUE)
                            .addComponent(tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(quantidadeMaterial, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(garantia, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(qtdGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(preco))
                        .addGap(71, 71, 71)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(garantia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(qtdGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(quantidadeMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(preco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(178, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox fornecedor;
    private javax.swing.JTextField garantia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField preco;
    private javax.swing.JComboBox qtdGarantia;
    private javax.swing.JTextField quantidadeMaterial;
    private javax.swing.JComboBox tipo;
    // End of variables declaration//GEN-END:variables
    
   // private PaisController paisController = new PaisController();
    
    private FornecedorController fornecedorController = new FornecedorController();
    private FornecimentoController fornecimentoController = new FornecimentoController();
    private GrupoMaterialController gmc = new GrupoMaterialController();
    private MaterialController materialController = new MaterialController();

    public AdicionaMaterialSP(LayoutManager layout) {
        super(layout);
    }
    
    private Fornecedor fornecedorTXT;
    private String tipoTXT;
    private int garantiaTXT;
    private int qtdMaterialTXT;
    private double precoTXT;
    
    
    @Override
    public void recebe() {
        fornecedorTXT = (Fornecedor)fornecedor.getSelectedItem();
        tipoTXT = (String)tipo.getSelectedItem();
        garantiaTXT = Integer.parseInt(garantia.getText());
        qtdMaterialTXT = Integer.parseInt(quantidadeMaterial.getText());
        precoTXT = Double.parseDouble(preco.getText());
    }

    @Override
    public boolean isValido() {
        return true;
    }

    @Override
    public boolean envia() {
        recebe();
        if(isValido()){
            //materialController.adicionar(null, ' ', '', null);
            return fornecimentoController.adicionar(null, fornecedorTXT, garantiaTXT,gmc.ultimo(),precoTXT, qtdMaterialTXT, tipoTXT);
        }
        return true;
    }

    @Override
    public void limpaTudo() {
        fornecedor.setSelectedIndex(0);
        tipo.setSelectedIndex(0);
        garantia.setText("");
        quantidadeMaterial.setText("");
        preco.getText();
    }
    
    private void preencherComboBoxCargo(){
        fornecedor.removeAllItems();
        List<Fornecedor> fornecedores = (List<Fornecedor>)fornecedorController.getFornecedors();
        for (Fornecedor forn: fornecedores) {
            fornecedor.addItem(forn);
        }
    }
}