package visao.paginas;


import controller.CompartimentoController;
import controller.FornecedorController;
import controller.FornecimentoController;
import controller.GrupoMaterialController;
import controller.MaterialController;
import java.awt.Container;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Compartimento;
import model.Fornecedor;
import model.GrupoMaterial;
import model.Material;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author elton
 */
public final class Ex extends javax.swing.JFrame {
    private final AdicionarFornecedor adicionarFornecedor;
    private final AdicionaMaterialPP adicionaMaterialPP;
    private final AdicionaMaterialSP adicionaMaterialSP;
    private final DefiniCapacidade definiCapacidade;
    private final AdicionaCompartimento adicionaCompartimento
                    = new AdicionaCompartimento();
    private final FornecedorController fornecedorController 
                    = new FornecedorController();
    private final GrupoMaterialController grupoMaterialController
                    = new GrupoMaterialController();
    private final FornecimentoController fornecimentoController 
                    = new FornecimentoController();
    private final MaterialController materialController 
                    = new MaterialController();
   
    private final CompartimentoController compartimentoController
                    = new CompartimentoController();
    /**
     * Creates new form Ex
     */
    public Ex() {
        initComponents();
        setLocationRelativeTo(null);
        materialJB.setSelected(true);
        //fornecedorJB.setSelected(true);
        adicionarFornecedor = new AdicionarFornecedor();
        adicionaMaterialPP = new AdicionaMaterialPP();
        adicionaMaterialSP = new AdicionaMaterialSP();
        definiCapacidade = new DefiniCapacidade();
        //adicionaCompartimento = new AdicionaCompartimento();
        desabilitarJbInferior();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        baseP = new javax.swing.JPanel();
        superiorP = new javax.swing.JPanel();
        voltarJB = new javax.swing.JButton();
        menuEsquerdaP = new javax.swing.JPanel();
        menuMaterialP = new javax.swing.JPanel();
        materialJB = new javax.swing.JToggleButton();
        fornecedorJB = new javax.swing.JToggleButton();
        estatisticaMaterialJB = new javax.swing.JToggleButton();
        menuCompartP = new javax.swing.JPanel();
        compartimentoJB = new javax.swing.JToggleButton();
        responsavelJB = new javax.swing.JToggleButton();
        estatisticaCompJB = new javax.swing.JToggleButton();
        centralP = new javax.swing.JPanel();
        tituloP = new javax.swing.JPanel();
        materialTXT = new javax.swing.JLabel();
        fornecedoresTXT = new javax.swing.JLabel();
        compartimentoTXT = new javax.swing.JLabel();
        conteudoP = new javax.swing.JPanel();
        conteudoMaterialP = new javax.swing.JPanel();
        conteudoMaterialDinamicoP = new javax.swing.JPanel();
        conteudoMaterial = new javax.swing.JPanel();
        listaMaterialP = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        listaMaterialGrupo = new javax.swing.JScrollPane();
        tbMaterialGrupo = new javax.swing.JTable();
        listaMaterialUnico = new javax.swing.JScrollPane();
        tbMaterialUnico = new javax.swing.JTable();
        escolheLista = new javax.swing.JComboBox();
        formAddMaterialP = new javax.swing.JTabbedPane();
        conteudoFornecedP = new javax.swing.JPanel();
        historicoFornecimentoP = new javax.swing.JPanel();
        formAddFornecedorP = new javax.swing.JTabbedPane();
        listaFornecedorP = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFornecdor = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        conteudoCompartimentoP = new javax.swing.JPanel();
        listaCompartimentoP = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbCompartimento = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        formAddCompartP = new javax.swing.JTabbedPane();
        conteudoResponsavelP = new javax.swing.JPanel();
        subMenu = new javax.swing.JPanel();
        subMenuMaterial = new javax.swing.JPanel();
        addMaterialJB = new javax.swing.JButton();
        listaMaterialJB = new javax.swing.JButton();
        editarMatJB = new javax.swing.JButton();
        subMenuFornec = new javax.swing.JPanel();
        historicoFornecimentoJB = new javax.swing.JButton();
        historicoFornecimentoJB1 = new javax.swing.JButton();
        editarFornecedorJB = new javax.swing.JButton();
        historicoFornecimentoJB3 = new javax.swing.JButton();
        subMenuComp = new javax.swing.JPanel();
        addCompBJ = new javax.swing.JButton();
        subMenuResponsavel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bjInferiorDireita = new javax.swing.JPanel();
        addFornecedorJB = new javax.swing.JButton();
        proximoPPJB = new javax.swing.JButton();
        addMaterialBJ = new javax.swing.JButton();
        addCompartimentoJB = new javax.swing.JButton();
        limpo2 = new javax.swing.JPanel();
        proximoAddFornJB = new javax.swing.JButton();
        bjInferiorCentral = new javax.swing.JPanel();
        anteriorAddMaterialJB = new javax.swing.JButton();
        cancelarFornecedorJB = new javax.swing.JButton();
        limpo = new javax.swing.JPanel();
        anteriorAddCompJB = new javax.swing.JButton();
        bjInferiorEsquerda = new javax.swing.JPanel();
        cancelarMaterialJB = new javax.swing.JButton();
        limpo1 = new javax.swing.JPanel();
        paginaInicialP = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SGP");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new java.awt.CardLayout());

        superiorP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        voltarJB.setText("Voltar");
        voltarJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarJBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout superiorPLayout = new javax.swing.GroupLayout(superiorP);
        superiorP.setLayout(superiorPLayout);
        superiorPLayout.setHorizontalGroup(
            superiorPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(superiorPLayout.createSequentialGroup()
                .addComponent(voltarJB)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        superiorPLayout.setVerticalGroup(
            superiorPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, superiorPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(voltarJB)
                .addContainerGap())
        );

        menuEsquerdaP.setBackground(new java.awt.Color(255, 255, 255));
        menuEsquerdaP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuEsquerdaP.setLayout(new java.awt.CardLayout());

        menuMaterialP.setBackground(new java.awt.Color(255, 255, 255));

        materialJB.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(materialJB);
        materialJB.setText("Material");
        materialJB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        materialJB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                materialJBStateChanged(evt);
            }
        });
        materialJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialJBActionPerformed(evt);
            }
        });

        fornecedorJB.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(fornecedorJB);
        fornecedorJB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/FornecedorEditado.jpg"))); // NOI18N
        fornecedorJB.setText("Fornecedor");
        fornecedorJB.setToolTipText("");
        fornecedorJB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fornecedorJB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fornecedorJB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fornecedorJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedorJBActionPerformed(evt);
            }
        });

        estatisticaMaterialJB.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(estatisticaMaterialJB);
        estatisticaMaterialJB.setText("Estatisticas");
        estatisticaMaterialJB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout menuMaterialPLayout = new javax.swing.GroupLayout(menuMaterialP);
        menuMaterialP.setLayout(menuMaterialPLayout);
        menuMaterialPLayout.setHorizontalGroup(
            menuMaterialPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(materialJB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fornecedorJB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(estatisticaMaterialJB, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );
        menuMaterialPLayout.setVerticalGroup(
            menuMaterialPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuMaterialPLayout.createSequentialGroup()
                .addComponent(materialJB, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fornecedorJB, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estatisticaMaterialJB, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 278, Short.MAX_VALUE))
        );

        menuEsquerdaP.add(menuMaterialP, "card2");

        menuCompartP.setBackground(new java.awt.Color(255, 255, 255));
        menuCompartP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        compartimentoJB.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(compartimentoJB);
        compartimentoJB.setText("Compartimento");
        compartimentoJB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        compartimentoJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compartimentoJBActionPerformed(evt);
            }
        });

        responsavelJB.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(responsavelJB);
        responsavelJB.setText("Responsavel");
        responsavelJB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        responsavelJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                responsavelJBActionPerformed(evt);
            }
        });

        estatisticaCompJB.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(estatisticaCompJB);
        estatisticaCompJB.setText("Estatisticas");
        estatisticaCompJB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        estatisticaCompJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estatisticaCompJBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuCompartPLayout = new javax.swing.GroupLayout(menuCompartP);
        menuCompartP.setLayout(menuCompartPLayout);
        menuCompartPLayout.setHorizontalGroup(
            menuCompartPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(compartimentoJB, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
            .addComponent(responsavelJB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(estatisticaCompJB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuCompartPLayout.setVerticalGroup(
            menuCompartPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuCompartPLayout.createSequentialGroup()
                .addComponent(compartimentoJB, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(responsavelJB, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estatisticaCompJB, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );

        menuEsquerdaP.add(menuCompartP, "card3");

        centralP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tituloP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tituloP.setLayout(new java.awt.CardLayout());

        materialTXT.setText("Dados de Materiais");
        tituloP.add(materialTXT, "card2");

        fornecedoresTXT.setText("Fornecedores");
        tituloP.add(fornecedoresTXT, "card3");

        compartimentoTXT.setText("Lista de Compartimentos");
        tituloP.add(compartimentoTXT, "card4");

        conteudoP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        conteudoP.setLayout(new java.awt.CardLayout());

        conteudoMaterialDinamicoP.setBackground(new java.awt.Color(51, 51, 0));
        conteudoMaterialDinamicoP.setLayout(new java.awt.CardLayout());

        conteudoMaterial.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        conteudoMaterial.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("Pesquisa");

        jPanel4.setLayout(new java.awt.CardLayout());

        tbMaterialGrupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Categoria", "Modelo", "Tipo", "Quantidade", "Preco"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listaMaterialGrupo.setViewportView(tbMaterialGrupo);
        if (tbMaterialGrupo.getColumnModel().getColumnCount() > 0) {
            tbMaterialGrupo.getColumnModel().getColumn(0).setResizable(false);
            tbMaterialGrupo.getColumnModel().getColumn(1).setResizable(false);
            tbMaterialGrupo.getColumnModel().getColumn(2).setResizable(false);
            tbMaterialGrupo.getColumnModel().getColumn(3).setResizable(false);
            tbMaterialGrupo.getColumnModel().getColumn(4).setResizable(false);
            tbMaterialGrupo.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel4.add(listaMaterialGrupo, "card2");

        tbMaterialUnico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Categoria", "Modelo", "Tipo", "Estado", "Preco", "Data Aquisicao"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbMaterialUnico.setColumnSelectionAllowed(true);
        listaMaterialUnico.setViewportView(tbMaterialUnico);
        tbMaterialUnico.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tbMaterialUnico.getColumnModel().getColumnCount() > 0) {
            tbMaterialUnico.getColumnModel().getColumn(0).setResizable(false);
            tbMaterialUnico.getColumnModel().getColumn(1).setResizable(false);
            tbMaterialUnico.getColumnModel().getColumn(2).setResizable(false);
            tbMaterialUnico.getColumnModel().getColumn(3).setResizable(false);
            tbMaterialUnico.getColumnModel().getColumn(4).setResizable(false);
            tbMaterialUnico.getColumnModel().getColumn(5).setResizable(false);
            tbMaterialUnico.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel4.add(listaMaterialUnico, "card3");

        escolheLista.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Unico", "Grupo" }));
        escolheLista.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                escolheListaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout listaMaterialPLayout = new javax.swing.GroupLayout(listaMaterialP);
        listaMaterialP.setLayout(listaMaterialPLayout);
        listaMaterialPLayout.setHorizontalGroup(
            listaMaterialPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaMaterialPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listaMaterialPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(listaMaterialPLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(escolheLista, 0, 77, Short.MAX_VALUE)))
                .addContainerGap())
        );
        listaMaterialPLayout.setVerticalGroup(
            listaMaterialPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaMaterialPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listaMaterialPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(escolheLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        conteudoMaterial.add(listaMaterialP, "card3");
        conteudoMaterial.add(formAddMaterialP, "card2");

        conteudoMaterialDinamicoP.add(conteudoMaterial, "card2");

        conteudoFornecedP.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout historicoFornecimentoPLayout = new javax.swing.GroupLayout(historicoFornecimentoP);
        historicoFornecimentoP.setLayout(historicoFornecimentoPLayout);
        historicoFornecimentoPLayout.setHorizontalGroup(
            historicoFornecimentoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
        );
        historicoFornecimentoPLayout.setVerticalGroup(
            historicoFornecimentoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );

        conteudoFornecedP.add(historicoFornecimentoP, "card3");
        conteudoFornecedP.add(formAddFornecedorP, "card2");

        tblFornecdor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Tipo", "Cidade", "Rua"
            }
        ));
        jScrollPane1.setViewportView(tblFornecdor);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout listaFornecedorPLayout = new javax.swing.GroupLayout(listaFornecedorP);
        listaFornecedorP.setLayout(listaFornecedorPLayout);
        listaFornecedorPLayout.setHorizontalGroup(
            listaFornecedorPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        listaFornecedorPLayout.setVerticalGroup(
            listaFornecedorPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaFornecedorPLayout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        conteudoFornecedP.add(listaFornecedorP, "card4");

        conteudoMaterialDinamicoP.add(conteudoFornecedP, "card3");

        conteudoCompartimentoP.setLayout(new java.awt.CardLayout());

        tbCompartimento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Designacao", "Tipo", "Responsavel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbCompartimento);
        if (tbCompartimento.getColumnModel().getColumnCount() > 0) {
            tbCompartimento.getColumnModel().getColumn(0).setResizable(false);
            tbCompartimento.getColumnModel().getColumn(1).setResizable(false);
            tbCompartimento.getColumnModel().getColumn(2).setResizable(false);
            tbCompartimento.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 689, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout listaCompartimentoPLayout = new javax.swing.GroupLayout(listaCompartimentoP);
        listaCompartimentoP.setLayout(listaCompartimentoPLayout);
        listaCompartimentoPLayout.setHorizontalGroup(
            listaCompartimentoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaCompartimentoPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
        );
        listaCompartimentoPLayout.setVerticalGroup(
            listaCompartimentoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaCompartimentoPLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        conteudoCompartimentoP.add(listaCompartimentoP, "card2");
        conteudoCompartimentoP.add(formAddCompartP, "card3");

        conteudoMaterialDinamicoP.add(conteudoCompartimentoP, "card4");

        javax.swing.GroupLayout conteudoResponsavelPLayout = new javax.swing.GroupLayout(conteudoResponsavelP);
        conteudoResponsavelP.setLayout(conteudoResponsavelPLayout);
        conteudoResponsavelPLayout.setHorizontalGroup(
            conteudoResponsavelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
        );
        conteudoResponsavelPLayout.setVerticalGroup(
            conteudoResponsavelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );

        conteudoMaterialDinamicoP.add(conteudoResponsavelP, "card5");

        subMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        subMenu.setLayout(new java.awt.CardLayout());

        addMaterialJB.setText("Novo");
        addMaterialJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMaterialJBActionPerformed(evt);
            }
        });

        listaMaterialJB.setText("Material");
        listaMaterialJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaMaterialJBActionPerformed(evt);
            }
        });

        editarMatJB.setText("Editar");

        javax.swing.GroupLayout subMenuMaterialLayout = new javax.swing.GroupLayout(subMenuMaterial);
        subMenuMaterial.setLayout(subMenuMaterialLayout);
        subMenuMaterialLayout.setHorizontalGroup(
            subMenuMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addMaterialJB, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
            .addComponent(listaMaterialJB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(editarMatJB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        subMenuMaterialLayout.setVerticalGroup(
            subMenuMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subMenuMaterialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listaMaterialJB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addMaterialJB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editarMatJB)
                .addContainerGap(336, Short.MAX_VALUE))
        );

        subMenu.add(subMenuMaterial, "card3");

        historicoFornecimentoJB.setText("Historico");
        historicoFornecimentoJB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        historicoFornecimentoJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historicoFornecimentoJBActionPerformed(evt);
            }
        });

        historicoFornecimentoJB1.setText("Novo");
        historicoFornecimentoJB1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        historicoFornecimentoJB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historicoFornecimentoJB1ActionPerformed(evt);
            }
        });

        editarFornecedorJB.setText("Editar");
        editarFornecedorJB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editarFornecedorJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarFornecedorJBActionPerformed(evt);
            }
        });

        historicoFornecimentoJB3.setText("Fornecedores");
        historicoFornecimentoJB3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        historicoFornecimentoJB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historicoFornecimentoJB3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subMenuFornecLayout = new javax.swing.GroupLayout(subMenuFornec);
        subMenuFornec.setLayout(subMenuFornecLayout);
        subMenuFornecLayout.setHorizontalGroup(
            subMenuFornecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(historicoFornecimentoJB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(historicoFornecimentoJB1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(editarFornecedorJB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(historicoFornecimentoJB3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        subMenuFornecLayout.setVerticalGroup(
            subMenuFornecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subMenuFornecLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(historicoFornecimentoJB3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(historicoFornecimentoJB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(historicoFornecimentoJB1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editarFornecedorJB)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        subMenu.add(subMenuFornec, "card2");

        addCompBJ.setText("Novo");
        addCompBJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCompBJActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subMenuCompLayout = new javax.swing.GroupLayout(subMenuComp);
        subMenuComp.setLayout(subMenuCompLayout);
        subMenuCompLayout.setHorizontalGroup(
            subMenuCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addCompBJ, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
        );
        subMenuCompLayout.setVerticalGroup(
            subMenuCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subMenuCompLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addCompBJ)
                .addContainerGap(398, Short.MAX_VALUE))
        );

        subMenu.add(subMenuComp, "card4");

        javax.swing.GroupLayout subMenuResponsavelLayout = new javax.swing.GroupLayout(subMenuResponsavel);
        subMenuResponsavel.setLayout(subMenuResponsavelLayout);
        subMenuResponsavelLayout.setHorizontalGroup(
            subMenuResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
        );
        subMenuResponsavelLayout.setVerticalGroup(
            subMenuResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        subMenu.add(subMenuResponsavel, "card5");

        javax.swing.GroupLayout conteudoMaterialPLayout = new javax.swing.GroupLayout(conteudoMaterialP);
        conteudoMaterialP.setLayout(conteudoMaterialPLayout);
        conteudoMaterialPLayout.setHorizontalGroup(
            conteudoMaterialPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conteudoMaterialPLayout.createSequentialGroup()
                .addComponent(conteudoMaterialDinamicoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        conteudoMaterialPLayout.setVerticalGroup(
            conteudoMaterialPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(conteudoMaterialDinamicoP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(subMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        conteudoP.add(conteudoMaterialP, "card2");

        javax.swing.GroupLayout centralPLayout = new javax.swing.GroupLayout(centralP);
        centralP.setLayout(centralPLayout);
        centralPLayout.setHorizontalGroup(
            centralPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(conteudoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        centralPLayout.setVerticalGroup(
            centralPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centralPLayout.createSequentialGroup()
                .addComponent(tituloP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conteudoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bjInferiorDireita.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bjInferiorDireita.setLayout(new java.awt.CardLayout());

        addFornecedorJB.setText("Concluir");
        addFornecedorJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFornecedorJBActionPerformed(evt);
            }
        });
        bjInferiorDireita.add(addFornecedorJB, "card3");

        proximoPPJB.setText("Proximo");
        proximoPPJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoPPJBActionPerformed(evt);
            }
        });
        bjInferiorDireita.add(proximoPPJB, "card5");

        addMaterialBJ.setText("Concluir");
        addMaterialBJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMaterialBJActionPerformed(evt);
            }
        });
        bjInferiorDireita.add(addMaterialBJ, "card6");

        addCompartimentoJB.setText("Concluir");
        addCompartimentoJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCompartimentoJBActionPerformed(evt);
            }
        });
        bjInferiorDireita.add(addCompartimentoJB, "card6");

        javax.swing.GroupLayout limpo2Layout = new javax.swing.GroupLayout(limpo2);
        limpo2.setLayout(limpo2Layout);
        limpo2Layout.setHorizontalGroup(
            limpo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        limpo2Layout.setVerticalGroup(
            limpo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        bjInferiorDireita.add(limpo2, "card4");

        proximoAddFornJB.setText("Proximo");
        proximoAddFornJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoAddFornJBActionPerformed(evt);
            }
        });
        bjInferiorDireita.add(proximoAddFornJB, "card7");

        bjInferiorCentral.setLayout(new java.awt.CardLayout());

        anteriorAddMaterialJB.setText("Anterior");
        anteriorAddMaterialJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorAddMaterialJBActionPerformed(evt);
            }
        });
        bjInferiorCentral.add(anteriorAddMaterialJB, "card2");

        cancelarFornecedorJB.setText("Cancelar");
        bjInferiorCentral.add(cancelarFornecedorJB, "card6");

        javax.swing.GroupLayout limpoLayout = new javax.swing.GroupLayout(limpo);
        limpo.setLayout(limpoLayout);
        limpoLayout.setHorizontalGroup(
            limpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        limpoLayout.setVerticalGroup(
            limpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        bjInferiorCentral.add(limpo, "card3");

        anteriorAddCompJB.setText("Anterior");
        anteriorAddCompJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorAddCompJBActionPerformed(evt);
            }
        });
        bjInferiorCentral.add(anteriorAddCompJB, "card5");

        bjInferiorEsquerda.setLayout(new java.awt.CardLayout());

        cancelarMaterialJB.setText("Cancelar");
        bjInferiorEsquerda.add(cancelarMaterialJB, "card2");

        javax.swing.GroupLayout limpo1Layout = new javax.swing.GroupLayout(limpo1);
        limpo1.setLayout(limpo1Layout);
        limpo1Layout.setHorizontalGroup(
            limpo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        limpo1Layout.setVerticalGroup(
            limpo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        bjInferiorEsquerda.add(limpo1, "card3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bjInferiorEsquerda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bjInferiorCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bjInferiorDireita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bjInferiorEsquerda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bjInferiorCentral, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bjInferiorDireita, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout basePLayout = new javax.swing.GroupLayout(baseP);
        baseP.setLayout(basePLayout);
        basePLayout.setHorizontalGroup(
            basePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basePLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(superiorP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, basePLayout.createSequentialGroup()
                        .addComponent(menuEsquerdaP, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(centralP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        basePLayout.setVerticalGroup(
            basePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basePLayout.createSequentialGroup()
                .addComponent(superiorP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuEsquerdaP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(centralP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(baseP, "card2");

        jButton1.setText("Material");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Compartimento");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paginaInicialPLayout = new javax.swing.GroupLayout(paginaInicialP);
        paginaInicialP.setLayout(paginaInicialPLayout);
        paginaInicialPLayout.setHorizontalGroup(
            paginaInicialPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaInicialPLayout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addGroup(paginaInicialPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(570, Short.MAX_VALUE))
        );
        paginaInicialPLayout.setVerticalGroup(
            paginaInicialPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaInicialPLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(465, Short.MAX_VALUE))
        );

        getContentPane().add(paginaInicialP, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void materialJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialJBActionPerformed
        trocaContainer(tituloP, materialTXT);
        trocaContainer(conteudoMaterialDinamicoP, conteudoMaterial);
        trocaContainer(subMenu, subMenuMaterial);
        trocaContainer(conteudoMaterial, listaMaterialP);
        desabilitarJbInferior();
    }//GEN-LAST:event_materialJBActionPerformed

    private void fornecedorJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedorJBActionPerformed
        trocaContainer(tituloP, fornecedoresTXT);
        trocaContainer(conteudoMaterialDinamicoP, conteudoFornecedP);
        trocaContainer(conteudoFornecedP, listaFornecedorP);
        trocaContainer(subMenu, subMenuFornec);
        editarFornecedorJB.setEnabled(false);
        desabilitarJbInferior();
        editarMatJB.setEnabled(false);
        listaFornecedor();
    }//GEN-LAST:event_fornecedorJBActionPerformed

    private void voltarJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarJBActionPerformed
        trocaContainer(this.getContentPane(), paginaInicialP);
        desabilitarJbInferior();
    }//GEN-LAST:event_voltarJBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        activaMaterial();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addMaterialJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMaterialJBActionPerformed
        trocaContainer(conteudoMaterial, formAddMaterialP);
        formAddMaterialP.add("1 de 2 Passos", adicionaMaterialPP);
        formAddMaterialP.add("2 de 2 Passos", adicionaMaterialSP);
        formAddMaterialP.setEnabledAt(1, false);
        
        trocaContainer(bjInferiorDireita, proximoPPJB);
        trocaContainer(bjInferiorCentral, anteriorAddMaterialJB);
        trocaContainer(bjInferiorEsquerda, cancelarMaterialJB);
        anteriorAddMaterialJB.setEnabled(false);
        
        editarMatJB.setEnabled(false);        
    }//GEN-LAST:event_addMaterialJBActionPerformed

    private void historicoFornecimentoJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historicoFornecimentoJBActionPerformed
        // TODO add your handling code here:
        trocaContainer(conteudoFornecedP, historicoFornecimentoP);
        desabilitarJbInferior();
        editarFornecedorJB.setEnabled(false);
    }//GEN-LAST:event_historicoFornecimentoJBActionPerformed

    private void historicoFornecimentoJB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historicoFornecimentoJB1ActionPerformed
        trocaContainer(conteudoFornecedP, formAddFornecedorP);
        formAddFornecedorP.add("Adicionar novo Fornecedor", adicionarFornecedor);
        trocaContainer(bjInferiorDireita, addFornecedorJB);
        editarFornecedorJB.setEnabled(false);
        trocaContainer(bjInferiorCentral, cancelarFornecedorJB);
        adicionarFornecedor.limpaTudo();
    }//GEN-LAST:event_historicoFornecimentoJB1ActionPerformed

    private void editarFornecedorJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarFornecedorJBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarFornecedorJBActionPerformed

    private void historicoFornecimentoJB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historicoFornecimentoJB3ActionPerformed
        trocaContainer(conteudoFornecedP, listaFornecedorP);
        desabilitarJbInferior();
        listaFornecedor();
    }//GEN-LAST:event_historicoFornecimentoJB3ActionPerformed

    private void addFornecedorJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFornecedorJBActionPerformed
        //adicionarFornecedor.isValido();
        //adicionarFornecedor.recebe();
        adicionarFornecedor.envia();
        trocaContainer(conteudoFornecedP, listaFornecedorP);
        listaFornecedor();
    }//GEN-LAST:event_addFornecedorJBActionPerformed

    private void proximoPPJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoPPJBActionPerformed
        formAddMaterialP.setEnabledAt(0, false);
        formAddMaterialP.setEnabledAt(1, true);
        formAddMaterialP.setSelectedIndex(1);
        trocaContainer(bjInferiorDireita, addMaterialBJ);
        anteriorAddMaterialJB.setEnabled(true);
        //trocaContainer(bjInferiorEsquerda, anteriorAddMaterialJB);
        //adicionaMaterialPP.envia();
    }//GEN-LAST:event_proximoPPJBActionPerformed

    private void anteriorAddMaterialJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorAddMaterialJBActionPerformed
        formAddMaterialP.setEnabledAt(0, true);
        formAddMaterialP.setEnabledAt(1, false);
        formAddMaterialP.setSelectedIndex(0);
        trocaContainer(bjInferiorDireita, proximoPPJB);
        //trocaContainer(bjInferiorEsquerda, limpo);
        anteriorAddMaterialJB.setEnabled(false);
    }//GEN-LAST:event_anteriorAddMaterialJBActionPerformed

    private void listaMaterialJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaMaterialJBActionPerformed
        trocaContainer(conteudoMaterial, listaMaterialP);
        editarMatJB.setEnabled(false);
    }//GEN-LAST:event_listaMaterialJBActionPerformed

    private void materialJBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_materialJBStateChanged
        // TODO add your handling code here:
        if(materialJB.isSelected()){
            editarMatJB.setEnabled(false);
        }
    }//GEN-LAST:event_materialJBStateChanged

    private void addMaterialBJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMaterialBJActionPerformed
        MaterialController materialController = new MaterialController();
        if(adicionaMaterialPP.envia()){
            if(adicionaMaterialSP.envia()){
                JOptionPane.showMessageDialog(null, "Sucesso", "Adicionado!!! Sucesso", JOptionPane.INFORMATION_MESSAGE);
                //materialController.adicionar(new Compartimento(), 'B', 'B');
                trocaContainer(conteudoMaterial, listaMaterialP);
                desabilitarJbInferior();
                adicionaMaterialPP.limpaTudo();
                adicionaMaterialSP.limpaTudo();
                editarMatJB.setEnabled(false);
                listaMaterialUnico();
                escolheLista.setSelectedIndex(0);
            }else{
                JOptionPane.showMessageDialog(null, "Falha ao Adicionar", "FALHA", JOptionPane.INFORMATION_MESSAGE);
            }      
        }else{
            JOptionPane.showMessageDialog(null, "FALHA", "Falha ao Adicionar", JOptionPane.ERROR);
        }
    }//GEN-LAST:event_addMaterialBJActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        activaCompartimento();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void compartimentoJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compartimentoJBActionPerformed
        activaCompartimento();
    }//GEN-LAST:event_compartimentoJBActionPerformed

    private void responsavelJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_responsavelJBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_responsavelJBActionPerformed

    private void estatisticaCompJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estatisticaCompJBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estatisticaCompJBActionPerformed

    private void addCompBJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCompBJActionPerformed
        trocaContainer(conteudoCompartimentoP, formAddCompartP);
        formAddCompartP.add("Adicionar Compartimento", adicionaCompartimento);
        formAddCompartP.add("Definir Capacidade", definiCapacidade);
        formAddCompartP.setEnabledAt(1, false);
        trocaContainer(bjInferiorDireita, proximoAddFornJB);
    }//GEN-LAST:event_addCompBJActionPerformed

    private void addCompartimentoJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCompartimentoJBActionPerformed
        if(adicionaCompartimento.envia()){

            formAddCompartP.setSelectedIndex(1);
        }
        //activaCompartimento();
    }//GEN-LAST:event_addCompartimentoJBActionPerformed

    private void escolheListaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_escolheListaItemStateChanged
        if(escolheLista.getSelectedItem().equals("Grupo")){
            trocaContainer(jPanel4, listaMaterialGrupo);
            listaMaterialGrupo();
        }else{
            trocaContainer(jPanel4, listaMaterialUnico);
            listaMaterialUnico();
        }
    }//GEN-LAST:event_escolheListaItemStateChanged

    private void proximoAddFornJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoAddFornJBActionPerformed
            formAddCompartP.setEnabledAt(1,true);
            formAddCompartP.setEnabledAt(0,false);
            formAddCompartP.setSelectedIndex(1);
            trocaContainer(bjInferiorDireita, addCompartimentoJB);
            trocaContainer(bjInferiorCentral,anteriorAddCompJB);
    }//GEN-LAST:event_proximoAddFornJBActionPerformed

    private void anteriorAddCompJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorAddCompJBActionPerformed
        formAddCompartP.setEnabledAt(0,true);
        formAddCompartP.setEnabledAt(1,false);
        formAddCompartP.setSelectedIndex(0);
        trocaContainer(bjInferiorDireita, proximoAddFornJB);
        trocaContainer(bjInferiorCentral, anteriorAddCompJB);
    }//GEN-LAST:event_anteriorAddCompJBActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    //UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCompBJ;
    private javax.swing.JButton addCompartimentoJB;
    private javax.swing.JButton addFornecedorJB;
    private javax.swing.JButton addMaterialBJ;
    private javax.swing.JButton addMaterialJB;
    private javax.swing.JButton anteriorAddCompJB;
    private javax.swing.JButton anteriorAddMaterialJB;
    private javax.swing.JPanel baseP;
    private javax.swing.JPanel bjInferiorCentral;
    private javax.swing.JPanel bjInferiorDireita;
    private javax.swing.JPanel bjInferiorEsquerda;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton cancelarFornecedorJB;
    private javax.swing.JButton cancelarMaterialJB;
    private javax.swing.JPanel centralP;
    private javax.swing.JToggleButton compartimentoJB;
    private javax.swing.JLabel compartimentoTXT;
    private javax.swing.JPanel conteudoCompartimentoP;
    private javax.swing.JPanel conteudoFornecedP;
    private javax.swing.JPanel conteudoMaterial;
    private javax.swing.JPanel conteudoMaterialDinamicoP;
    private javax.swing.JPanel conteudoMaterialP;
    private javax.swing.JPanel conteudoP;
    private javax.swing.JPanel conteudoResponsavelP;
    private javax.swing.JButton editarFornecedorJB;
    private javax.swing.JButton editarMatJB;
    private javax.swing.JComboBox escolheLista;
    private javax.swing.JToggleButton estatisticaCompJB;
    private javax.swing.JToggleButton estatisticaMaterialJB;
    private javax.swing.JTabbedPane formAddCompartP;
    private javax.swing.JTabbedPane formAddFornecedorP;
    private javax.swing.JTabbedPane formAddMaterialP;
    private javax.swing.JToggleButton fornecedorJB;
    private javax.swing.JLabel fornecedoresTXT;
    private javax.swing.JButton historicoFornecimentoJB;
    private javax.swing.JButton historicoFornecimentoJB1;
    private javax.swing.JButton historicoFornecimentoJB3;
    private javax.swing.JPanel historicoFornecimentoP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel limpo;
    private javax.swing.JPanel limpo1;
    private javax.swing.JPanel limpo2;
    private javax.swing.JPanel listaCompartimentoP;
    private javax.swing.JPanel listaFornecedorP;
    private javax.swing.JScrollPane listaMaterialGrupo;
    private javax.swing.JButton listaMaterialJB;
    private javax.swing.JPanel listaMaterialP;
    private javax.swing.JScrollPane listaMaterialUnico;
    private javax.swing.JToggleButton materialJB;
    private javax.swing.JLabel materialTXT;
    private javax.swing.JPanel menuCompartP;
    private javax.swing.JPanel menuEsquerdaP;
    private javax.swing.JPanel menuMaterialP;
    private javax.swing.JPanel paginaInicialP;
    private javax.swing.JButton proximoAddFornJB;
    private javax.swing.JButton proximoPPJB;
    private javax.swing.JToggleButton responsavelJB;
    private javax.swing.JPanel subMenu;
    private javax.swing.JPanel subMenuComp;
    private javax.swing.JPanel subMenuFornec;
    private javax.swing.JPanel subMenuMaterial;
    private javax.swing.JPanel subMenuResponsavel;
    private javax.swing.JPanel superiorP;
    private javax.swing.JTable tbCompartimento;
    private javax.swing.JTable tbMaterialGrupo;
    private javax.swing.JTable tbMaterialUnico;
    private javax.swing.JTable tblFornecdor;
    private javax.swing.JPanel tituloP;
    private javax.swing.JButton voltarJB;
    // End of variables declaration//GEN-END:variables


public void trocaContainer(Container base, Container novo){
        base.removeAll();
        base.repaint();
        base.revalidate();
        base.add(novo);
        base.repaint();
        base.revalidate();
    }
    
    public void limpaContainer(Container componente){
        componente.removeAll();
        componente.repaint();
        componente.revalidate();
    }
    
    public void desabilitarJbInferior(){
        trocaContainer(bjInferiorDireita, limpo2);
        trocaContainer(bjInferiorCentral, limpo);
        trocaContainer(bjInferiorEsquerda, limpo1);
    }
    
    public void activaCompartimento(){
        trocaContainer(getContentPane(), baseP);
        trocaContainer(conteudoMaterialDinamicoP, conteudoCompartimentoP);
        trocaContainer(subMenu, subMenuComp);
        trocaContainer(menuEsquerdaP, menuCompartP);
        trocaContainer(tituloP, compartimentoTXT);
        trocaContainer(conteudoCompartimentoP, listaCompartimentoP);
        desabilitarJbInferior();
        compartimentoJB.setSelected(true);
        listaCompartimento();
    }
    
    public void activaMaterial(){
        trocaContainer(getContentPane(), baseP);
        trocaContainer(menuEsquerdaP,menuMaterialP);
        trocaContainer(tituloP,materialTXT);
        trocaContainer(conteudoMaterialDinamicoP,conteudoMaterial);
        trocaContainer(subMenu,subMenuMaterial);
        trocaContainer(jPanel4, listaMaterialUnico);
        materialJB.setSelected(true);
        escolheLista.setSelectedIndex(0);
        listaMaterialUnico();
        desabilitarJbInferior();
    }
    
    
    public  void listaFornecedor(){
        List<Fornecedor> fornecedores = (List<Fornecedor>)fornecedorController.getFornecedors();
        DefaultTableModel tableModel = (DefaultTableModel) tblFornecdor.getModel();
        
        while(tableModel.getRowCount() > 0){
            tableModel.removeRow(0);
        }

        for(Fornecedor f: fornecedores){
            String [] linhaForn = new  String[]{f.getNome(),f.getEmail(),f.getEndereco().getCidade(),f.getEndereco().getRua()};
            tableModel.addRow(linhaForn);
        }
    }
    
    public void listaMaterialGrupo(){
        List<GrupoMaterial> materials = grupoMaterialController.getGrupoMaterials();
        DefaultTableModel tableModel = (DefaultTableModel)tbMaterialGrupo.getModel();
        
        while(tableModel.getRowCount() > 0){
            tableModel.removeRow(0);
        }
        
        for(GrupoMaterial gm: materials){
            String codigo, categoria, modelo,tipo,qtd,preco;
            codigo = ""+gm.getId();
            categoria = gm.getCategoriaMaterial_ID().getDesignacao();
            modelo = gm.getModelo();
            tipo = gm.getCategoriaMaterial_ID().getIdentiTipo();
            qtd = fornecimentoController.quantidadePorGrupo(gm.getId())+"";
            preco = fornecimentoController.precoMaterialPorGrupo(gm.getId())+"";
            
            
            String [] linha = new String[]{codigo,categoria,modelo,tipo,qtd,preco};
            tableModel.addRow(linha);
        }
    }
    
    public void listaMaterialUnico(){
        List<Material> materials = materialController.getMaterials();
        
        DefaultTableModel tableModel = (DefaultTableModel) tbMaterialUnico.getModel();
        
        while(tableModel.getRowCount() > 0){
            tableModel.removeRow(0);
        }
        
        for(Material material: materials){
            String codigo, categoria, modelo,tipo,estado,preco;
            codigo = material.getId()+"";
            categoria = material.getGrupoMaterial().getCategoriaMaterial_ID().getDesignacao();
            modelo = material.getGrupoMaterial().getModelo();
            tipo = material.getGrupoMaterial().getCategoriaMaterial_ID().getIdentiTipo();
            estado = material.getEstado()+"";
            preco = "0";
            
            String []linha = new String[]{codigo,categoria,modelo,tipo,estado,preco};
            tableModel.addRow(linha);
        }
    }
    
    public void listaCompartimento(){
        List<Compartimento> compartimentos = compartimentoController.geCompartimentos();
        DefaultTableModel tableModel = (DefaultTableModel) tbCompartimento.getModel();
    
        while(tableModel.getRowCount() > 0){
            tableModel.removeRow(0);
}
        
        for(Compartimento compartimento: compartimentos){
            String codigo,designacao,tipo,responsavel;
            codigo = compartimento.getId()+"";
            designacao = compartimento.getDescricao();
            tipo = compartimento.getTipoCompartimento().getDesignacao();
            responsavel = "Nao definido";
            
            String []linha = new String[]{codigo,designacao,tipo,responsavel};
            tableModel.addRow(linha);
        }
    }
}